# docker-compose file for Prowlarr https://hub.docker.com/r/linuxserver/prowlarr
# using 2 spaces as indent.

---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockermnts/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
