# docker-compose file for my download stack
# using 2 spaces as indent.
---

services:
  krusader:
    container_name: krusader
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - USER_LOCALES='en_DK.UTF-8 UTF-8'
      - CUSTOM_RES_W=1920
      - CUSTOM_RES_W=1080

    ports:
      - 8080:8080

    volumes:
      - /opt/dockermnts/krusader/config:/config
      - /netmounts:/netmounts
      - /mnt:/mnt