# docker-compose file for home assistant core
# using 2 spaces as indent.
---
version: "2.1"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /opt/dockermnts/homeassistant/config:/config
      - /opt/dockermnts/homeassistant/backup:/backupfiles
    ports:
      - 8123:8123
    restart: unless-stopped