# docker-compose file for my download stack
# using 2 spaces as indent.
---
version: "3"

services:

### jackett ###
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/dockermnts/jackett/config:/config
      - /netmounts/new/Torrents/Incomplete/torrentfiles:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped