# docker-compose file for my download stack
# using 2 spaces as indent.
---
version: "3"

services:

### gluetun ###
  gluetun:
    # container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/dockermnts/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      #- OPENVPN_USER=abc <-- in the secrets file
      #- OPENVPN_PASSWORD=abc <-- in the secrets file
      - SERVER_REGIONS=Switzerland
    env_file:
      - secrets.txt
    ports:
      - 8112:8112 # Deluge port
      - 6881:6881 # Deluge port
      - 6881:6881/udp # Deluge port
      - 9117:9117 # Jackett port
      - 8989:8989 # Sonarr port
      - 7878:7878 # Radarr port
    dns:
      - 1.1.1.1

### Deluge ###
  deluge:
    container_name: deluge
    network_mode: "service:gluetun"
    restart: unless-stopped
    image: linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - DELUGE_LOGLEVEL=error # optional
    volumes:
      #- /opt/dockermnts/deluge/config:/config
      - /netmounts/new/Torrents/Complete/:/downloads
      - /completetest:/downloads
    #ports:
    #  - 8112:8112
    #  - 6881:6881
    #  - 6881:6881/udp
    depends_on:
      - gluetun

### Jackett ###
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/dockermnts/jackett/config:/config
      - /netmounts/new/Torrents/Incomplete/torrentfiles:/downloads
    ports:
      # - 9117:9117
    restart: unless-stopped

### Sonarr ###
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockermnts/sonarr/config:/config
      - /netmounts/tv:/tv #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      #- 8989:8989
    restart: unless-stopped

### Radarr ###
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/dockermnts/radarr/config:/config
      - /netmounts/movies:/movies #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      #- 7878:7878
    restart: unless-stopped

